import React, { useState, useEffect, useMemo } from 'react';
import { DollarSign, TrendingUp, Building, Receipt, Download, Filter, Search, CreditCard, CheckCircle, XCircle, User, FileText, Mail, ArrowRightLeft, Plus } from 'lucide-react';
import { accountingService } from '../services/accountingService';
import RoleLayout from '../components/RoleLayout';
import '../components/RoleLayout.css';
import '../pages/TechnicianDashboard.css';

const AccountingDashboard = () => {
  const [activeTab, setActiveTab] = useState('overview');
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [showLandlordPaymentModal, setShowLandlordPaymentModal] = useState(false);
  const [showReceiptModal, setShowReceiptModal] = useState(false);
  const [showApprovalModal, setShowApprovalModal] = useState(false);
  const [selectedPayment, setSelectedPayment] = useState(null);
  const [notifications, setNotifications] = useState([]);
  const [showExpenseModal, setShowExpenseModal] = useState(false);
  const [loading, setLoading] = useState(false);
  
  // API Data States
  const [overviewData, setOverviewData] = useState(null);
  const [tenantPayments, setTenantPayments] = useState([]);
  const [landlordPayments, setLandlordPayments] = useState([]);
  const [collections, setCollections] = useState([]);
  const [expenses, setExpenses] = useState([]);
  const [monthlySummary, setMonthlySummary] = useState(null);

  const addNotification = (message, type = 'info') => {
    const id = Date.now();
    setNotifications(prev => [...prev, { id, message, type }]);
    setTimeout(() => {
      setNotifications(prev => prev.filter(n => n.id !== id));
    }, 3000);
  };

  const tabs = useMemo(
    () => [
      { id: 'overview', label: 'Overview', icon: DollarSign },
      { id: 'collections', label: 'Collections', icon: TrendingUp },
      { id: 'payments', label: 'Landlord Payments', icon: Building },
      { id: 'tenant-payments', label: 'Tenant Payments', icon: CreditCard },
      { id: 'reports', label: 'Reports', icon: Receipt },
      { id: 'expenses', label: 'Expenses', icon: FileText }
    ],
    []
  );

  // Load data from APIs
  const loadData = async () => {
    try {
      setLoading(true);
      console.log('Loading accounting dashboard data...');
      
      const [overview, tenantPaymentsData, landlordPaymentsData, collectionsData, expensesData, summary] = await Promise.all([
        accountingService.getOverview(),
        accountingService.getTenantPayments(),
        accountingService.getLandlordPayments(),
        accountingService.getCollections(),
        accountingService.getExpenses(),
        accountingService.getMonthlySummary()
      ]);

      setOverviewData(overview);
      setTenantPayments(tenantPaymentsData);
      setLandlordPayments(landlordPaymentsData);
      setCollections(collectionsData);
      setExpenses(expensesData);
      setMonthlySummary(summary);
      
      console.log('Accounting data loaded successfully:', { overview, tenantPaymentsData, landlordPaymentsData, collectionsData, expensesData, summary });
    } catch (error) {
      console.error('Failed to load accounting data:', error);
      addNotification('Failed to load dashboard data', 'error');
    } finally {
      setLoading(false);
    }
  };

  // Load data on component mount
  useEffect(() => {
    loadData();
  }, []);

  const generateReceipt = async (payment) => {
    try {
      setLoading(true);
      const updatedPayment = await accountingService.generateReceipt(payment.ID);
      
      // Update local state
      setTenantPayments(prev => prev.map(p => 
        p.ID === payment.ID ? updatedPayment : p
      ));

      // Generate downloadable receipt
      const receiptContent = `
        RENTAL PAYMENT RECEIPT
        =====================
        
        Receipt No: ${updatedPayment.ReceiptNumber}
        Date: ${new Date().toLocaleDateString()}
        
        Tenant: ${payment.Tenant}
        Property: ${payment.Property}
        Amount Paid: ${payment.Amount.toFixed(2)} XOF
        Charge Type: ${payment.ChargeType || 'N/A'}
        Payment Method: ${payment.Method}
        Payment Date: ${new Date(payment.Date).toLocaleDateString()}
        
        Status: CONFIRMED
        
        Thank you for your payment!
        
        Generated by: Accounting Department
        Generated on: ${new Date().toLocaleString()}
      `;

      const blob = new Blob([receiptContent], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `receipt-${updatedPayment.ReceiptNumber}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);

      addNotification('Receipt generated and downloaded!', 'success');
    } catch (error) {
      console.error('Failed to generate receipt:', error);
      addNotification('Failed to generate receipt', 'error');
    } finally {
      setLoading(false);
    }
  };

  const sendReceipt = async (payment) => {
    if (!payment.ReceiptNumber) {
      addNotification('Generate receipt before sending.', 'warning');
      return;
    }
    
    try {
      setLoading(true);
      const email = prompt('Enter tenant email address:');
      if (email) {
        await accountingService.sendReceipt(payment.ID, email);
        addNotification(`Receipt sent to ${email}`, 'success');
      }
    } catch (error) {
      console.error('Failed to send receipt:', error);
      addNotification('Failed to send receipt', 'error');
    } finally {
      setLoading(false);
    }
  };

  const transferToLandlord = async (paymentId) => {
    try {
      setLoading(true);
      await accountingService.transferToLandlord(paymentId);
      
      // Update local state
      setLandlordPayments(prev => prev.map(p => 
        p.ID === paymentId ? { ...p, Status: 'Paid' } : p
      ));
      
      addNotification(`Transfer to landlord completed for payment #${paymentId}.`, 'success');
    } catch (error) {
      console.error('Failed to transfer to landlord:', error);
      addNotification('Failed to transfer to landlord', 'error');
    } finally {
      setLoading(false);
    }
  };

  const approvePayment = async (payment) => {
    try {
      setLoading(true);
      const updatedPayment = await accountingService.approveTenantPayment(payment.ID);
      
      // Update local state
      setTenantPayments(prev => prev.map(p => 
        p.ID === payment.ID ? updatedPayment : p
      ));
      
      addNotification(`Payment approved for ${payment.Tenant}`, 'success');
    } catch (error) {
      console.error('Failed to approve payment:', error);
      addNotification('Failed to approve payment', 'error');
    } finally {
      setLoading(false);
    }
  };

  const confirmApproval = () => {
    if (selectedPayment) {
      setTenantPayments(prev => prev.map(p => 
        p.ID === selectedPayment.ID 
          ? { ...p, Status: 'Approved', ReceiptNumber: p.ReceiptNumber || `RCP-${Date.now()}` }
          : p
      ));

      addNotification(`Payment from ${selectedPayment.Tenant} approved successfully!`, 'success');
      setShowApprovalModal(false);
      setSelectedPayment(null);
    }
  };

  const rejectPayment = (payment) => {
    setTenantPayments(prev => prev.map(p => 
      p.ID === payment.ID 
        ? { ...p, Status: 'Rejected' }
        : p
    ));

    addNotification(`Payment from ${payment.Tenant} rejected.`, 'warning');
  };

  const renderOverview = () => (
    <div className="overview-section">
      <div className="section-header">
        <div>
          <h2>Accounting Overview</h2>
          <p>Financial summary and balance tracking</p>
        </div>
      </div>

      <div className="dashboard-overview accounting-overview">
        <div className="overview-card">
          <div className="card-label">
            <span>Total Available Balance</span>
          </div>
          <div className="card-value">
            <span>
              {overviewData ? `${overviewData.netRevenue?.toFixed(2) || '0.00'} XOF` : 'Loading...'}
            </span>
            <small>Current balance</small>
          </div>
        </div>
        <div className="overview-card">
          <div className="card-label">
            <span>Total Collected This Month</span>
          </div>
          <div className="card-value">
            <span>
              {overviewData ? `${overviewData.totalTenantPayments?.toFixed(2) || '0.00'} XOF` : 'Loading...'}
            </span>
            <small>November 2024</small>
          </div>
        </div>
        <div className="overview-card">
          <div className="card-label">
            <span>Total Transferred to Landlords</span>
          </div>
          <div className="card-value">
            <span>
              {overviewData ? `${overviewData.totalLandlordPayments?.toFixed(2) || '0.00'} XOF` : 'Loading...'}
            </span>
            <small>This month</small>
          </div>
        </div>
        <div className="overview-card">
          <div className="card-label">
            <span>Company Commission Earned</span>
          </div>
          <div className="card-value">
            <span>
              {overviewData ? `${overviewData.pendingPayments || 0} XOF` : 'Loading...'}
            </span>
            <small>This month</small>
          </div>
        </div>
      </div>
    </div>
  );

  const renderCollections = () => (
    <div className="collections-section">
      <div className="section-header">
        <div>
          <h2>Real-time Collections Tracking</h2>
          <p>Track rent and deposit payments per building</p>
        </div>
      </div>

      <div className="filters-section" style={{ display: 'flex', gap: '12px', marginBottom: '20px', flexWrap: 'wrap' }}>
        <select className="filter-select">
          <option value="">All Buildings/Properties</option>
          <option value="123-main">123 Main St</option>
          <option value="456-oak">456 Oak Ave</option>
          <option value="789-pine">789 Pine Ln</option>
          <option value="321-elm">321 Elm St</option>
        </select>
        <select className="filter-select">
          <option value="">All Landlords</option>
          <option value="john-smith">John Smith</option>
          <option value="jane-doe">Jane Doe</option>
          <option value="bob-johnson">Bob Johnson</option>
          <option value="alice-brown">Alice Brown</option>
        </select>
        <select className="filter-select">
          <option value="">All Periods</option>
          <option value="current-month">Current Month</option>
          <option value="last-month">Last Month</option>
          <option value="last-3-months">Last 3 Months</option>
        </select>
        <select className="filter-select">
          <option value="">All Payment Status</option>
          <option value="collected">Collected</option>
          <option value="pending">Pending</option>
          <option value="overdue">Overdue</option>
        </select>
        <select className="filter-select">
          <option value="">All Charge Types</option>
          <option value="rent">Rent</option>
          <option value="deposit">Deposit</option>
          <option value="late-fee">Late Fee</option>
          <option value="maintenance">Maintenance</option>
        </select>
      </div>

      {loading ? (
        <div className="loading">Loading collections...</div>
      ) : collections.length === 0 ? (
        <div className="no-data">No collections found</div>
      ) : (
        <div className="data-table-wrapper">
          <table className="data-table">
            <thead>
              <tr>
                <th>Building/Property</th>
                <th>Landlord</th>
                <th>Amount</th>
                <th>Payment Status</th>
                <th>Charge Type</th>
                <th>Date</th>
                <th className="table-menu"></th>
              </tr>
            </thead>
            <tbody>
              {collections.map((collection, index) => (
                <tr key={collection.ID || `collection-${index}`}>
                  <td>
                    <span className="row-primary">{collection.Building || 'N/A'}</span>
                  </td>
                  <td>{collection.Landlord || 'N/A'}</td>
                  <td>{collection.Amount?.toFixed(2) || '0.00'} XOF</td>
                  <td>
                    <span className={`status-badge ${(collection.Status || 'unknown').toLowerCase()}`}>
                      {collection.Status || 'Unknown'}
                    </span>
                  </td>
                  <td>{collection.ChargeType || 'N/A'}</td>
                  <td>{collection.Date ? new Date(collection.Date).toLocaleDateString() : 'N/A'}</td>
                  <td className="table-menu">
                    <div className="table-actions">
                      <button className="table-action-button view">View</button>
                      <button className="table-action-button edit">Receipt</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );

  const renderPayments = () => (
    <div className="payments-section">
      <div className="section-header">
        <div>
          <h2>Landlord Payment Table</h2>
          <p>Net payments after commission deduction</p>
        </div>
        <button 
          className="btn-primary" 
          onClick={() => setShowLandlordPaymentModal(true)}
          disabled={loading}
        >
          <Plus size={18} />
          Record Payment
        </button>
      </div>

      <div className="filters-section" style={{ display: 'flex', gap: '12px', marginBottom: '20px', flexWrap: 'wrap' }}>
        <select className="filter-select">
          <option value="">All Landlords</option>
          <option value="john-smith">John Smith</option>
          <option value="jane-doe">Jane Doe</option>
          <option value="bob-johnson">Bob Johnson</option>
        </select>
        <select className="filter-select">
          <option value="">All Buildings</option>
          <option value="123-main">123 Main St</option>
          <option value="456-oak">456 Oak Ave</option>
          <option value="789-pine">789 Pine Ln</option>
        </select>
        <select className="filter-select">
          <option value="">All Periods</option>
          <option value="current-month">Current Month</option>
          <option value="last-month">Last Month</option>
        </select>
      </div>

      {loading ? (
        <div className="loading">Loading landlord payments...</div>
      ) : landlordPayments.length === 0 ? (
        <div className="no-data">No landlord payments found</div>
      ) : (
        <div className="data-table-wrapper">
          <table className="data-table">
            <thead>
              <tr>
                <th>Landlord</th>
                <th>Building</th>
                <th>Net Amount</th>
                <th>Commission</th>
                <th>Transaction Type</th>
                <th>Date</th>
                <th>Status</th>
                <th className="table-menu"></th>
              </tr>
            </thead>
            <tbody>
              {landlordPayments.map((payment, index) => (
                <tr key={payment.ID || `landlord-payment-${index}`}>
                  <td>
                    <span className="row-primary">{payment.Landlord || 'N/A'}</span>
                  </td>
                  <td>{payment.Building || 'N/A'}</td>
                  <td>{payment.NetAmount?.toFixed(2) || '0.00'} XOF</td>
                  <td>{payment.Commission?.toFixed(2) || '0.00'} XOF</td>
                  <td>Payout</td>
                  <td>{payment.Date ? new Date(payment.Date).toLocaleDateString() : 'N/A'}</td>
                  <td>
                    <span className={`status-badge ${(payment.Status || 'unknown').toLowerCase()}`}>
                      {payment.Status || 'Unknown'}
                    </span>
                  </td>
                  <td className="table-menu">
                    <div className="table-actions">
                      <button className="table-action-button view">View</button>
                      <button className="table-action-button edit" onClick={() => transferToLandlord(payment.ID)} title="Automatic Transfer">
                        Transfer
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );

  const renderReports = () => (
    <div className="reports-section">
      <div className="section-header">
        <div>
          <h2>Monthly Financial Reports</h2>
          <p>Generate and download comprehensive financial reports</p>
        </div>
        <button className="btn-primary">
          <Download size={18} />
          Generate Monthly Report
        </button>
      </div>

      <div className="data-table-wrapper" style={{ marginBottom: '32px' }}>
        <table className="data-table">
          <thead>
            <tr>
              <th>Building</th>
              <th>Rent Collected</th>
              <th>Deposits Collected</th>
              <th>Commission</th>
              <th>Net to Landlords</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <span className="row-primary">123 Main St</span>
              </td>
              <td>8,500 XOF</td>
              <td>1,200 XOF</td>
              <td>950 XOF</td>
              <td>8,750 XOF</td>
            </tr>
            <tr>
              <td>
                <span className="row-primary">456 Oak Ave</span>
              </td>
              <td>6,200 XOF</td>
              <td>0 XOF</td>
              <td>620 XOF</td>
              <td>5,580 XOF</td>
            </tr>
            <tr>
              <td>
                <span className="row-primary">789 Pine Ln</span>
              </td>
              <td>12,800 XOF</td>
              <td>500 XOF</td>
              <td>1,330 XOF</td>
              <td>11,970 XOF</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="section-header" style={{ marginBottom: '20px' }}>
        <div>
          <h2>Recent Reports</h2>
          <p>Download previously generated reports</p>
        </div>
      </div>

      {loading ? (
        <div className="loading">Loading reports...</div>
      ) : (
        <div className="data-table-wrapper">
          <table className="data-table">
            <thead>
              <tr>
                <th>Report Name</th>
                <th>Generated Date</th>
                <th className="table-menu"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <span className="row-primary">November 2024 Financial Report</span>
                </td>
                <td>Nov 1, 2024</td>
                <td className="table-menu">
                  <div className="table-actions">
                    <button className="table-action-button view">
                      <Download size={14} />
                      Download
                    </button>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <span className="row-primary">October 2024 Building Performance</span>
                </td>
                <td>Oct 31, 2024</td>
                <td className="table-menu">
                  <div className="table-actions">
                    <button className="table-action-button view">
                      <Download size={14} />
                      Download
                    </button>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <span className="row-primary">Q3 2024 Commission Report</span>
                </td>
                <td>Oct 1, 2024</td>
                <td className="table-menu">
                  <div className="table-actions">
                    <button className="table-action-button view">
                      <Download size={14} />
                      Download
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      )}
    </div>
  );

  const renderTenantPayments = () => (
    <div className="tenant-payments-section">
      <div className="section-header">
        <div>
          <h2>Tenant Payment Management</h2>
          <p>Review, approve, and manage tenant payments</p>
        </div>
        <button 
          className="btn-primary" 
          onClick={() => setShowPaymentModal(true)}
          disabled={loading}
        >
          <Plus size={18} />
          Record New Payment
        </button>
      </div>

      <div className="filters-section" style={{ display: 'flex', gap: '12px', marginBottom: '20px', flexWrap: 'wrap' }}>
        <select className="filter-select">
          <option value="">All Payments</option>
          <option value="pending">Pending</option>
          <option value="approved">Approved</option>
          <option value="rejected">Rejected</option>
        </select>
        <select className="filter-select">
          <option value="">All Methods</option>
          <option value="cash">Cash</option>
          <option value="mobile">Mobile Money</option>
          <option value="bank">Bank Transfer</option>
        </select>
        <input type="text" placeholder="Search by tenant..." className="search-input" style={{ padding: '10px 14px', borderRadius: '12px', border: '1px solid rgba(15, 31, 96, 0.12)', background: '#f7f8ff', minWidth: '200px' }} />
      </div>

      {loading ? (
        <div className="loading">Loading tenant payments...</div>
      ) : tenantPayments.length === 0 ? (
        <div className="no-data">No tenant payments found</div>
      ) : (
        <div className="data-table-wrapper">
          <table className="data-table">
            <thead>
              <tr>
                <th>Tenant</th>
                <th>Property</th>
                <th>Amount</th>
                <th>Method</th>
                <th>Date</th>
                <th>Status</th>
                <th>Receipt</th>
                <th className="table-menu"></th>
              </tr>
            </thead>
            <tbody>
              {tenantPayments.map((payment, index) => (
                <tr key={payment.ID || `payment-${index}`}>
                  <td>
                    <span className="row-primary">{payment.Tenant || 'N/A'}</span>
                  </td>
                  <td>{payment.Property || 'N/A'}</td>
                  <td>{payment.Amount?.toFixed(2) || '0.00'} XOF</td>
                  <td>{payment.Method || 'N/A'}</td>
                  <td>{payment.Date ? new Date(payment.Date).toLocaleDateString() : 'N/A'}</td>
                  <td>
                    <span className={`status-badge ${(payment.Status || 'unknown').toLowerCase()}`}>
                      {payment.Status || 'Unknown'}
                    </span>
                  </td>
                  <td>
                    {payment.ReceiptNumber ? (
                      <span className="row-primary">{payment.ReceiptNumber}</span>
                    ) : (
                      <span style={{ color: 'rgba(15, 31, 96, 0.5)' }}>No Receipt</span>
                    )}
                  </td>
                  <td className="table-menu">
                    <div className="table-actions">
                      {payment.Status === 'Pending' && (
                        <>
                          <button 
                            className="table-action-button edit"
                            onClick={() => approvePayment(payment)}
                            title="Approve Payment"
                          >
                            Approve
                          </button>
                          <button 
                            className="table-action-button delete"
                            onClick={() => rejectPayment(payment)}
                            title="Reject Payment"
                          >
                            Reject
                          </button>
                        </>
                      )}
                      <button 
                        className="table-action-button view"
                        onClick={() => generateReceipt(payment)}
                        title="Generate Receipt"
                      >
                        Receipt
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );

  const renderExpenses = () => (
    <div className="expenses-section">
      <div className="section-header">
        <div>
          <h2>Expense Management</h2>
          <p>Track expenses by building or for SAAF IMMO</p>
        </div>
        <button 
          className="btn-primary" 
          onClick={() => setShowExpenseModal(true)}
          disabled={loading}
        >
          <Plus size={18} />
          Add Expense
        </button>
      </div>

      {loading ? (
        <div className="loading">Loading expenses...</div>
      ) : expenses.length === 0 ? (
        <div className="no-data">No expenses found</div>
      ) : (
        <div className="data-table-wrapper">
          <table className="data-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Scope</th>
                <th>Building</th>
                <th>Category</th>
                <th>Amount</th>
                <th>Notes</th>
                <th className="table-menu"></th>
              </tr>
            </thead>
            <tbody>
              {expenses.map((exp, index) => (
                <tr key={exp.ID || exp.id || `expense-${index}`}>
                  <td>{exp.Date ? new Date(exp.Date).toLocaleDateString() : (exp.date || 'N/A')}</td>
                  <td>{exp.Scope || exp.scope || 'N/A'}</td>
                  <td>
                    <span className="row-primary">{exp.Building || exp.building || 'N/A'}</span>
                  </td>
                  <td>{exp.Category || exp.category || 'N/A'}</td>
                  <td>{(exp.Amount || exp.amount || 0).toFixed(2)} XOF</td>
                  <td>{exp.Notes || exp.notes || 'N/A'}</td>
                  <td className="table-menu">
                    <div className="table-actions">
                      <button className="table-action-button view">View</button>
                      <button className="table-action-button edit">Edit</button>
                      <button className="table-action-button delete">Delete</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );

  const renderContent = (tabId = activeTab) => {
    switch (tabId) {
      case 'overview':
        return renderOverview();
      case 'collections':
        return renderCollections();
      case 'payments':
        return renderPayments();
      case 'tenant-payments':
        return renderTenantPayments();
      case 'reports':
        return renderReports();
      case 'expenses':
        return renderExpenses();
      default:
        return renderOverview();
    }
  };

  const layoutMenu = useMemo(
    () =>
      tabs.map(tab => ({
        ...tab,
        onSelect: () => setActiveTab(tab.id),
        active: activeTab === tab.id
      })),
    [tabs, activeTab]
  );

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    window.location.href = '/';
  };

  return (
    <>
      <RoleLayout
        brand={{ name: 'SAAF IMMO', caption: 'Accounting', logo: 'SAAF', logoImage: `${process.env.PUBLIC_URL}/download.jpeg` }}
        menu={layoutMenu}
        activeId={activeTab}
        onActiveChange={setActiveTab}
        onLogout={handleLogout}
      >
        {({ activeId }) => (
          <div className="content-body accounting-content">
            {loading && <div className="loading-indicator">Loading data...</div>}
            {renderContent(activeId || activeTab)}
          </div>
        )}
      </RoleLayout>

      <div className="notifications-container">
        {notifications.map((notification, index) => (
          <div key={notification.id || `notification-${index}`} className={`notification notification-${notification.type}`}>
            <span>{notification.message}</span>
            <button onClick={() => setNotifications(prev => prev.filter(n => n.id !== notification.id))}>×</button>
          </div>
        ))}
      </div>

      {/* Payment Recording Modal */}
      {showPaymentModal && (
        <div className="modal-overlay" onClick={() => setShowPaymentModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Record New Payment</h3>
              <button className="modal-close" onClick={() => setShowPaymentModal(false)}>×</button>
            </div>
            <div className="modal-body">
              <form onSubmit={async (e) => {
                e.preventDefault();
                try {
                  setLoading(true);
                  const formData = new FormData(e.target);
                  const paymentData = {
                    tenant: formData.get('tenant'),
                    property: formData.get('property'),
                    amount: parseFloat(formData.get('amount')),
                    method: formData.get('method'),
                    chargeType: formData.get('chargeType') || 'Rent'
                  };
                  
                  // Call the backend API
                  const newPayment = await accountingService.recordTenantPayment(paymentData);
                  
                  // Update local state with the response from backend
                  setTenantPayments(prev => [newPayment, ...prev]);
                  addNotification('Payment recorded successfully!', 'success');
                  setShowPaymentModal(false);
                  
                  // Reset form
                  e.target.reset();
                } catch (error) {
                  console.error('Error recording payment:', error);
                  addNotification('Failed to record payment. Please try again.', 'error');
                } finally {
                  setLoading(false);
                }
              }}>
                <div className="form-group">
                  <label htmlFor="tenant">Tenant Name</label>
                  <input type="text" name="tenant" required placeholder="Enter tenant name" />
                </div>
                <div className="form-group">
                  <label htmlFor="property">Property</label>
                  <select name="property" required>
                    <option value="">Select Property</option>
                    <option value="123 Main St">123 Main St</option>
                    <option value="456 Oak Ave">456 Oak Ave</option>
                    <option value="789 Pine Ln">789 Pine Ln</option>
                    <option value="321 Elm St">321 Elm St</option>
                  </select>
                </div>
                <div className="form-group">
                  <label htmlFor="amount">Amount</label>
                  <input type="number" name="amount" step="0.01" required placeholder="Enter amount" />
                </div>
                <div className="form-group">
                  <label htmlFor="method">Payment Method</label>
                  <select name="method" required>
                    <option value="">Select Method</option>
                    <option value="Cash">Cash</option>
                    <option value="Mobile Money">Mobile Money</option>
                    <option value="Bank Transfer">Bank Transfer</option>
                  </select>
                </div>
                <div className="form-group">
                  <label htmlFor="chargeType">Charge Type</label>
                  <select name="chargeType" required>
                    <option value="">Select Charge</option>
                    <option value="Rent">Rent</option>
                    <option value="Deposit">Deposit</option>
                    <option value="Late Fee">Late Fee</option>
                    <option value="Maintenance">Maintenance</option>
                  </select>
                </div>
                <div className="modal-footer">
                  <button type="button" className="action-button secondary" onClick={() => setShowPaymentModal(false)}>
                    Cancel
                  </button>
                  <button type="submit" className="action-button primary" disabled={loading}>
                    {loading ? 'Recording...' : 'Record Payment'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* Payment Approval Modal */}
      {showApprovalModal && selectedPayment && (
        <div className="modal-overlay" onClick={() => setShowApprovalModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Confirm Payment Approval</h3>
              <button className="modal-close" onClick={() => setShowApprovalModal(false)}>×</button>
            </div>
            <div className="modal-body">
              <div className="approval-details">
                <h4>Payment Details:</h4>
                <p><strong>Tenant:</strong> {selectedPayment.tenant}</p>
                <p><strong>Property:</strong> {selectedPayment.property}</p>
                <p><strong>Amount:</strong> {selectedPayment.amount.toFixed(2)} XOF</p>
                <p><strong>Method:</strong> {selectedPayment.method}</p>
                <p><strong>Date:</strong> {selectedPayment.date}</p>
              </div>
              <p>Are you sure you want to approve this payment?</p>
              <div className="modal-footer">
                <button type="button" className="action-button secondary" onClick={() => setShowApprovalModal(false)}>
                  Cancel
                </button>
                <button type="button" className="action-button primary" onClick={confirmApproval}>
                  Approve Payment
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Landlord Payment Recording Modal */}
      {showLandlordPaymentModal && (
        <div className="modal-overlay" onClick={() => setShowLandlordPaymentModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Record Landlord Payment</h3>
              <button className="modal-close" onClick={() => setShowLandlordPaymentModal(false)}>×</button>
            </div>
            <div className="modal-body">
              <form onSubmit={async (e) => {
                e.preventDefault();
                try {
                  setLoading(true);
                  const formData = new FormData(e.target);
                  const paymentData = {
                    landlord: formData.get('landlord'),
                    building: formData.get('building'),
                    netAmount: parseFloat(formData.get('netAmount')),
                    commission: parseFloat(formData.get('commission'))
                  };
                  
                  // Call the backend API
                  const newPayment = await accountingService.recordLandlordPayment(paymentData);
                  
                  // Update local state with the response from backend
                  setLandlordPayments(prev => [newPayment, ...prev]);
                  addNotification('Landlord payment recorded successfully!', 'success');
                  setShowLandlordPaymentModal(false);
                  
                  // Reset form
                  e.target.reset();
                } catch (error) {
                  console.error('Error recording landlord payment:', error);
                  addNotification('Failed to record landlord payment. Please try again.', 'error');
                } finally {
                  setLoading(false);
                }
              }}>
                <div className="form-group">
                  <label htmlFor="landlord">Landlord Name</label>
                  <input type="text" name="landlord" required placeholder="Enter landlord name" />
                </div>
                <div className="form-group">
                  <label htmlFor="building">Building</label>
                  <select name="building" required>
                    <option value="">Select Building</option>
                    <option value="123 Main St">123 Main St</option>
                    <option value="456 Oak Ave">456 Oak Ave</option>
                    <option value="789 Pine Ln">789 Pine Ln</option>
                    <option value="321 Elm St">321 Elm St</option>
                    <option value="654 Maple Dr">654 Maple Dr</option>
                  </select>
                </div>
                <div className="form-group">
                  <label htmlFor="netAmount">Net Amount ($)</label>
                  <input type="number" name="netAmount" step="0.01" required placeholder="Enter net amount" />
                </div>
                <div className="form-group">
                  <label htmlFor="commission">Commission ($)</label>
                  <input type="number" name="commission" step="0.01" required placeholder="Enter commission amount" />
                </div>
                <div className="modal-footer">
                  <button type="button" className="action-button secondary" onClick={() => setShowLandlordPaymentModal(false)}>
                    Cancel
                  </button>
                  <button type="submit" className="action-button primary" disabled={loading}>
                    {loading ? 'Recording...' : 'Record Payment'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* Expense Modal */}
      {showExpenseModal && (
        <div className="modal-overlay" onClick={() => setShowExpenseModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Add Expense</h3>
              <button className="modal-close" onClick={() => setShowExpenseModal(false)}>×</button>
            </div>
            <div className="modal-body">
              <form onSubmit={async (e) => {
                e.preventDefault();
                try {
                  setLoading(true);
                  const formData = new FormData(e.target);
                  const expenseData = {
                    scope: formData.get('scope'),
                    building: formData.get('scope') === 'SAAF IMMO' ? '-' : formData.get('building'),
                    category: formData.get('category'),
                    amount: parseFloat(formData.get('amount')),
                    date: formData.get('date'),
                    notes: formData.get('notes')
                  };
                  
                  // Call the backend API
                  const newExpense = await accountingService.addExpense(expenseData);
                  
                  // Update local state with the response from backend
                  setExpenses(prev => [newExpense, ...prev]);
                  addNotification('Expense added successfully!', 'success');
                  setShowExpenseModal(false);
                  
                  // Reset form
                  e.target.reset();
                } catch (error) {
                  console.error('Error adding expense:', error);
                  addNotification('Failed to add expense. Please try again.', 'error');
                } finally {
                  setLoading(false);
                }
              }}>
                <div className="form-group">
                  <label>Scope</label>
                  <select name="scope" required>
                    <option value="">Select Scope</option>
                    <option value="Building">Building</option>
                    <option value="SAAF IMMO">SAAF IMMO</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Building (if Building scope)</label>
                  <select name="building">
                    <option value="">Select Building</option>
                    <option value="123 Main St">123 Main St</option>
                    <option value="456 Oak Ave">456 Oak Ave</option>
                    <option value="789 Pine Ln">789 Pine Ln</option>
                    <option value="321 Elm St">321 Elm St</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Category</label>
                  <select name="category" required>
                    <option value="">Select Category</option>
                    <option value="Maintenance">Maintenance</option>
                    <option value="Utilities">Utilities</option>
                    <option value="Taxes">Taxes</option>
                    <option value="Software">Software</option>
                    <option value="Other">Other</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Amount</label>
                  <input type="number" name="amount" step="0.01" required />
                </div>
                <div className="form-group">
                  <label>Date</label>
                  <input type="date" name="date" required />
                </div>
                <div className="form-group">
                  <label>Notes</label>
                  <input type="text" name="notes" placeholder="Optional" />
                </div>
                <div className="modal-footer">
                  <button type="button" className="action-button secondary" onClick={() => setShowExpenseModal(false)}>
                    Cancel
                  </button>
                  <button type="submit" className="action-button primary" disabled={loading}>
                    {loading ? 'Adding...' : 'Add Expense'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default AccountingDashboard;