import React from 'react';
import { Download } from 'lucide-react';
import { t } from '../../utils/i18n';

const ReportsTab = (props) => {
  const { loading, selectedReportType, setSelectedReportType, reportStartDate, setReportStartDate, reportEndDate, setReportEndDate, reportPeriod, setReportPeriod, reportData, setReportData, loadReport, exportReportToCSV, overviewData, collections, landlordPayments, tenants, landlords } = props;

  const reportTypes = [
    { value: 'global-financial', label: 'Global Financial Report' }, { value: 'rent-property-management', label: 'Rent & Property Management' }, { value: 'deposit-report', label: 'Deposit Report' }, { value: 'owner-report', label: 'Owner Report' }, { value: 'sales-report', label: 'Sales Report' }, { value: 'property-report', label: 'Property Report' }, { value: 'tax-report', label: 'Tax Report' }, { value: 'management-summary', label: 'Management Summary' },
    { value: 'payments-by-period', label: t('accounting.paymentsByPeriod') }, { value: 'commissions-by-period', label: t('accounting.commissionsByPeriod') }, { value: 'refunds', label: t('accounting.refundsReport') }, { value: 'payments-by-building', label: t('accounting.paymentsByBuilding') }, { value: 'payments-by-tenant', label: t('accounting.paymentsByTenant') }, { value: 'expenses-by-period', label: t('accounting.expensesByPeriod') }, { value: 'collections-by-period', label: t('accounting.collectionsByPeriod') }, { value: 'building-performance', label: t('accounting.buildingPerformance') }, { value: 'payment-status', label: t('accounting.paymentStatusBreakdown') }
  ];

  const renderReportTable = () => {
    if (!reportData) return null;
    const summary = reportData.summary || [];
    switch (selectedReportType) {
      case 'payments-by-period': return <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Period</th><th>Total Count</th><th>Total Amount</th><th>Successful Count</th><th>Successful Amount</th><th>Failed Count</th><th>Failed Amount</th></tr></thead><tbody>{summary.map((item, i) => <tr key={i}><td>{item.period}</td><td>{item.totalCount||0}</td><td>{(item.totalAmount||0).toFixed(2)} XOF</td><td>{item.successfulCount||0}</td><td>{(item.successfulAmount||0).toFixed(2)} XOF</td><td>{item.failedCount||0}</td><td>{(item.failedAmount||0).toFixed(2)} XOF</td></tr>)}</tbody></table></div>;
      case 'commissions-by-period': return <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Period</th><th>Total Commission</th><th>Payment Count</th><th>Average Commission</th></tr></thead><tbody>{summary.map((item, i) => <tr key={i}><td>{item.period}</td><td>{(item.totalCommission||0).toFixed(2)} XOF</td><td>{item.paymentCount||0}</td><td>{(item.averageCommission||0).toFixed(2)} XOF</td></tr>)}</tbody></table></div>;
      case 'payments-by-building': return <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Building</th><th>Total Amount</th><th>Payment Count</th><th>Rent</th><th>Deposit</th><th>Other</th></tr></thead><tbody>{summary.map((item, i) => <tr key={i}><td><span className="sa-cell-title">{item.building||'N/A'}</span></td><td>{(item.totalAmount||0).toFixed(2)} XOF</td><td>{item.paymentCount||0}</td><td>{(item.rentAmount||0).toFixed(2)} XOF</td><td>{(item.depositAmount||0).toFixed(2)} XOF</td><td>{(item.otherAmount||0).toFixed(2)} XOF</td></tr>)}</tbody></table></div>;
      case 'payments-by-tenant': return <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Tenant</th><th>Property</th><th>Total Amount</th><th>Count</th><th>Last Payment</th></tr></thead><tbody>{summary.map((item, i) => <tr key={i}><td><span className="sa-cell-title">{item.tenant||'N/A'}</span></td><td>{item.property||'N/A'}</td><td>{(item.totalAmount||0).toFixed(2)} XOF</td><td>{item.paymentCount||0}</td><td>{item.lastPaymentDate ? new Date(item.lastPaymentDate).toLocaleDateString() : 'N/A'}</td></tr>)}</tbody></table></div>;
      case 'building-performance': return <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Building</th><th>Collections</th><th>Expenses</th><th>Net Revenue</th><th>Occupancy</th><th>Collection Rate</th></tr></thead><tbody>{(reportData.buildings||[]).map((item, i) => <tr key={i}><td><span className="sa-cell-title">{item.building||'N/A'}</span></td><td>{(item.totalCollections||0).toFixed(2)} XOF</td><td>{(item.totalExpenses||0).toFixed(2)} XOF</td><td>{(item.netRevenue||0).toFixed(2)} XOF</td><td>{(item.occupancyRate||0).toFixed(2)}%</td><td>{(item.paymentCollectionRate||0).toFixed(2)}%</td></tr>)}</tbody></table></div>;
      case 'payment-status': return <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Status</th><th>Count</th><th>Total Amount</th></tr></thead><tbody>{(reportData.statusBreakdown||[]).map((item, i) => <tr key={i}><td><span className={`sa-status-pill ${(item.status||'').toLowerCase()}`}>{item.status||'N/A'}</span></td><td>{item.count||0}</td><td>{(item.totalAmount||0).toFixed(2)} XOF</td></tr>)}</tbody></table></div>;
      case 'global-financial': return <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Category</th><th>Total Revenue</th><th>Total Expenses</th><th>Net Profit</th></tr></thead><tbody><tr><td>Overall</td><td>{(overviewData?.totalCollectedThisMonth||0).toFixed(2)} XOF</td><td>{(overviewData?.totalExpensesThisMonth||0).toFixed(2)} XOF</td><td>{((overviewData?.totalCollectedThisMonth||0)-(overviewData?.totalExpensesThisMonth||0)).toFixed(2)} XOF</td></tr></tbody></table></div>;
      case 'management-summary': return <div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '24px' }}><div style={{ padding: '20px', backgroundColor: '#f0f9ff', borderRadius: '8px', border: '1px solid #93c5fd' }}><p style={{ margin: 0, color: '#6b7280', fontSize: '0.875rem' }}>Total Collections</p><p style={{ margin: '8px 0 0 0', fontSize: '1.5rem', fontWeight: '600', color: '#0284c7' }}>{(overviewData?.totalCollectedThisMonth||0).toFixed(2)} XOF</p></div><div style={{ padding: '20px', backgroundColor: '#fef2f2', borderRadius: '8px', border: '1px solid #fca5a5' }}><p style={{ margin: 0, color: '#6b7280', fontSize: '0.875rem' }}>Total Expenses</p><p style={{ margin: '8px 0 0 0', fontSize: '1.5rem', fontWeight: '600', color: '#dc2626' }}>{(overviewData?.totalExpensesThisMonth||0).toFixed(2)} XOF</p></div><div style={{ padding: '20px', backgroundColor: '#f0fdf4', borderRadius: '8px', border: '1px solid #86efac' }}><p style={{ margin: 0, color: '#6b7280', fontSize: '0.875rem' }}>Net Profit</p><p style={{ margin: '8px 0 0 0', fontSize: '1.5rem', fontWeight: '600', color: '#059669' }}>{((overviewData?.totalCollectedThisMonth||0)-(overviewData?.totalExpensesThisMonth||0)).toFixed(2)} XOF</p></div></div><div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody><tr><td>Total Properties</td><td>{collections.length}</td></tr><tr><td>Active Tenants</td><td>{overviewData?.activeTenants||overviewData?.numberOfActiveTenants||tenants.length}</td></tr><tr><td>Total Owners</td><td>{landlords.length}</td></tr></tbody></table></div></div>;
      default: return summary.length > 0 ? <div className="sa-table-wrapper"><table className="sa-table"><thead><tr><th>Period</th><th>Total Amount</th><th>Count</th></tr></thead><tbody>{summary.map((item, i) => <tr key={i}><td>{item.period}</td><td>{(item.totalAmount||0).toFixed(2)} XOF</td><td>{item.expenseCount||item.collectionCount||0}</td></tr>)}</tbody></table></div> : null;
    }
  };

  return (
    <div><div className="sa-section-card">
      <div className="sa-section-header"><div><h2>Financial Reports</h2><p>Generate comprehensive reports on payments, commissions, refunds, and more</p></div></div>
      <div style={{ padding: '20px', borderBottom: '1px solid #e5e7eb' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px', marginBottom: '16px' }}>
          <div className="form-group"><label>Report Type</label><select value={selectedReportType} onChange={(e) => { setSelectedReportType(e.target.value); setReportData(null); }} style={{ width: '100%', padding: '8px', borderRadius: '6px', border: '1px solid #d1d5db' }}>{reportTypes.map(type => <option key={type.value} value={type.value}>{type.label}</option>)}</select></div>
          {(selectedReportType === 'payments-by-period' || selectedReportType === 'commissions-by-period') && <div className="form-group"><label>Period</label><select value={reportPeriod} onChange={(e) => setReportPeriod(e.target.value)} style={{ width: '100%', padding: '8px', borderRadius: '6px', border: '1px solid #d1d5db' }}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></div>}
          <div className="form-group"><label>Start Date</label><input type="date" value={reportStartDate} onChange={(e) => setReportStartDate(e.target.value)} style={{ width: '100%', padding: '8px', borderRadius: '6px', border: '1px solid #d1d5db' }} /></div>
          <div className="form-group"><label>End Date</label><input type="date" value={reportEndDate} onChange={(e) => setReportEndDate(e.target.value)} style={{ width: '100%', padding: '8px', borderRadius: '6px', border: '1px solid #d1d5db' }} /></div>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}><button className="sa-primary-cta" onClick={loadReport} disabled={loading}>Generate Report</button>{reportData && <button className="sa-outline-button" onClick={exportReportToCSV} disabled={loading}><Download size={18} /> Export to CSV</button>}</div>
      </div>
      {loading ? <div className="loading" style={{ padding: '40px', textAlign: 'center' }}>Generating report...</div> : reportData ? (
        <div style={{ padding: '20px' }}>
          <div style={{ marginBottom: '20px' }}><h3 style={{ marginBottom: '8px' }}>{reportTypes.find(t2 => t2.value === selectedReportType)?.label}</h3><p style={{ color: '#6b7280', fontSize: '0.875rem' }}>Period: {reportData.startDate} to {reportData.endDate}{reportData.period && ` | Grouped by: ${reportData.period}`}</p></div>
          {renderReportTable()}
        </div>
      ) : <div style={{ padding: '40px', textAlign: 'center', color: '#9ca3af' }}>Select filters and click "Generate Report" to view report data</div>}
    </div></div>
  );
};
export default ReportsTab;
